from .auth import router as auth
from .users import router as users
from .clients import router as clients
from .audits import router as audits
from .reports import router as reports
from .competitors import router as competitors
from .internal_linking import router as internal_linking
from .dashboard import router as dashboard
from .backlinks import router as backlinks
from .ai import router as ai
from .ai_settings import router as ai_settings
from .google_integration import router as google_integration