from __future__ import annotations

"""
Professional SEO report exporter for Boost Rankers AI SEO OS.

This module is intentionally isolated from the audit engine. It only converts
an already-generated Report (and its related Audit metadata) into a professional
PDF or DOCX download.

Dependencies:
    python-docx
    reportlab
"""

import io
import re
from dataclasses import dataclass
from html import unescape
from typing import Any

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


NAVY = "0B1220"
BLUE = "123B5D"
TEAL = "0F766E"
LIGHT = "F5F7FA"
BORDER = "D7DEE8"
TEXT = "263241"
MUTED = "667085"
CRITICAL = "B42318"
HIGH = "B54708"
MEDIUM = "175CD3"
LOW = "667085"


@dataclass
class Finding:
    severity: str
    title: str
    detail: str = ""
    recommendation: str = ""
    evidence: str = ""
    url: str = ""


def _clean(value: Any) -> str:
    if value is None:
        return ""
    value = unescape(str(value))
    value = re.sub(r"\s+", " ", value)
    return value.strip()


def _audit_value(audit: Any, *names: str, default: Any = 0) -> Any:
    for name in names:
        try:
            value = getattr(audit, name, None)
        except Exception:
            value = None
        if value is not None:
            return value
    return default


def _format_score(value: Any) -> str:
    try:
        return f"{float(value):.1f}/100"
    except Exception:
        return "N/A"


def _extract_website(report: Any) -> str:
    audit = getattr(report, "audit", None)
    website = _audit_value(audit, "website", "url", default="")
    if website:
        return _clean(website)

    match = re.search(r"https?://[^\s|)>]+", _clean(getattr(report, "content", "")))
    return match.group(0).rstrip(".,") if match else ""


def _parse_scorecard(content: str) -> dict[str, str]:
    result: dict[str, str] = {}
    areas = (
        "Technical SEO",
        "Content SEO",
        "Local SEO",
        "Schema",
        "EEAT",
        "Internal Linking",
        "Competitor",
        "Backlink",
        "AI Search",
    )
    for area in areas:
        match = re.search(
            rf"{re.escape(area)}(?:\s+SEO)?\s*\|\s*([0-9]+(?:\.[0-9]+)?/100)",
            content,
            re.I,
        )
        if match:
            result[area] = match.group(1)
            continue
        match = re.search(
            rf"{re.escape(area)}(?:\s+SEO)?[^\n]{{0,80}}?([0-9]+(?:\.[0-9]+)?/100)",
            content,
            re.I,
        )
        if match:
            result[area] = match.group(1)
    return result


def _parse_dict_findings(content: str) -> list[Finding]:
    """
    Converts legacy Python-dict/JSON-like finding text into structured findings.
    This prevents raw {'severity': ...} output in exports.
    """
    findings: list[Finding] = []

    pattern = re.compile(
        r"\{['\"]severity['\"]\s*:\s*['\"](?P<severity>[^'\"]+)['\"]"
        r".*?['\"]title['\"]\s*:\s*['\"](?P<title>.*?)['\"]"
        r".*?['\"]detail['\"]\s*:\s*['\"](?P<detail>.*?)['\"]"
        r".*?['\"]recommendation['\"]\s*:\s*['\"](?P<recommendation>.*?)['\"]"
        r".*?['\"]evidence['\"]\s*:\s*['\"](?P<evidence>.*?)['\"]\s*\}",
        re.I | re.S,
    )

    for match in pattern.finditer(content):
        data = match.groupdict()
        findings.append(
            Finding(
                severity=_clean(data["severity"]).lower(),
                title=_clean(data["title"]),
                detail=_clean(data["detail"]),
                recommendation=_clean(data["recommendation"]),
                evidence=_clean(data["evidence"]),
            )
        )
    return findings


def _parse_markdown_findings(content: str) -> list[Finding]:
    """
    Parses the normal report markdown generated by the audit service.
    It recognizes severity-led lines and subsequent evidence/recommendation text.
    """
    findings: list[Finding] = []
    lines = content.splitlines()
    current: Finding | None = None

    severity_re = re.compile(
        r"^\s*(?:[-*]\s*)?(CRITICAL|HIGH|MEDIUM|LOW)\s*(?:—|-|:)\s*(.+)$",
        re.I,
    )

    for raw in lines:
        line = _clean(raw)
        if not line:
            continue

        match = severity_re.match(line)
        if match:
            if current:
                findings.append(current)
            current = Finding(
                severity=match.group(1).lower(),
                title=_clean(match.group(2)),
            )
            urls = re.findall(r"https?://[^\s<>'\")]+", current.title)
            if urls:
                current.url = urls[0].rstrip(".,")
            continue

        if current is None:
            continue

        lower = line.lower()
        if lower.startswith("evidence:"):
            current.evidence = _clean(line.split(":", 1)[1])
        elif lower.startswith("recommended action:"):
            current.recommendation = _clean(line.split(":", 1)[1])
        elif lower.startswith("recommendation:"):
            current.recommendation = _clean(line.split(":", 1)[1])
        elif lower.startswith("what the crawl reports:"):
            current.detail = _clean(line.split(":", 1)[1])
        elif current.detail == "" and not line.startswith("#"):
            current.detail = line

    if current:
        findings.append(current)

    return findings


def extract_findings(content: str) -> list[Finding]:
    findings = _parse_dict_findings(content)
    if findings:
        return findings

    return _parse_markdown_findings(content)


def _extract_urls(content: str) -> list[str]:
    urls = re.findall(r"https?://[^\s<>'\")\],]+", content)
    output: list[str] = []
    seen: set[str] = set()
    for url in urls:
        url = url.rstrip(".,;:")
        if url not in seen:
            seen.add(url)
            output.append(url)
    return output


def _issue_counts(findings: list[Finding]) -> dict[str, int]:
    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for finding in findings:
        severity = finding.severity.lower()
        if severity in counts:
            counts[severity] += 1
    return counts


def _safe_filename(value: str, extension: str) -> str:
    value = re.sub(r"[\\/:*?\"<>|]+", "-", value).strip(" .")
    value = value or "seo-audit-report"
    return f"{value}.{extension}"


# ---------------- DOCX ----------------

def _shade_cell(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = tc_pr.find(qn("w:shd"))
    if shd is None:
        shd = OxmlElement("w:shd")
        tc_pr.append(shd)
    shd.set(qn("w:fill"), fill)


def _set_cell_text(
    cell,
    text: Any,
    *,
    bold: bool = False,
    color: str = TEXT,
    size: float = 8.5,
) -> None:
    cell.text = ""
    paragraph = cell.paragraphs[0]
    paragraph.paragraph_format.space_after = Pt(0)
    run = paragraph.add_run(_clean(text))
    run.bold = bold
    run.font.name = "Aptos"
    run.font.size = Pt(size)
    run.font.color.rgb = RGBColor.from_string(color)
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER


def _set_cell_margins(cell, top=90, start=100, bottom=90, end=100) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    tc_mar = tc_pr.first_child_found_in("w:tcMar")
    if tc_mar is None:
        tc_mar = OxmlElement("w:tcMar")
        tc_pr.append(tc_mar)

    for name, value in (
        ("top", top),
        ("start", start),
        ("bottom", bottom),
        ("end", end),
    ):
        node = tc_mar.find(qn(f"w:{name}"))
        if node is None:
            node = OxmlElement(f"w:{name}")
            tc_mar.append(node)
        node.set(qn("w:w"), str(value))
        node.set(qn("w:type"), "dxa")


def _add_bottom_border(cell, color=BORDER, size="6") -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    borders = tc_pr.first_child_found_in("w:tcBorders")
    if borders is None:
        borders = OxmlElement("w:tcBorders")
        tc_pr.append(borders)

    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), size)
    bottom.set(qn("w:space"), "0")
    bottom.set(qn("w:color"), color)
    borders.append(bottom)


def _add_docx_page_number(paragraph) -> None:
    paragraph.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = paragraph.add_run("Page ")
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instruction = OxmlElement("w:instrText")
    instruction.set(qn("xml:space"), "preserve")
    instruction.text = "PAGE"
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.append(begin)
    run._r.append(instruction)
    run._r.append(end)


def build_docx(report: Any) -> tuple[bytes, str]:
    document = Document()

    section = document.sections[0]
    section.top_margin = Inches(0.62)
    section.bottom_margin = Inches(0.62)
    section.left_margin = Inches(0.68)
    section.right_margin = Inches(0.68)

    styles = document.styles
    styles["Normal"].font.name = "Aptos"
    styles["Normal"].font.size = Pt(9)
    styles["Normal"].font.color.rgb = RGBColor.from_string(TEXT)

    for name, size, color in (
        ("Title", 25, NAVY),
        ("Heading 1", 17, NAVY),
        ("Heading 2", 12.5, BLUE),
        ("Heading 3", 10.5, NAVY),
    ):
        style = styles[name]
        style.font.name = "Aptos Display"
        style.font.size = Pt(size)
        style.font.bold = True
        style.font.color.rgb = RGBColor.from_string(color)

    header = section.header.paragraphs[0]
    header.text = "BOOST RANKERS  •  AI SEO OS"
    header.runs[0].font.size = Pt(8)
    header.runs[0].font.bold = True
    header.runs[0].font.color.rgb = RGBColor.from_string(BLUE)

    footer = section.footer.paragraphs[0]
    footer.text = "Evidence-based SEO audit  •  "
    footer.runs[0].font.size = Pt(7.5)
    footer.runs[0].font.color.rgb = RGBColor.from_string(MUTED)
    _add_docx_page_number(footer)

    website = _extract_website(report)
    audit = getattr(report, "audit", None)
    content = _clean(getattr(report, "content", "") or "")
    findings = extract_findings(content)
    counts = _issue_counts(findings)
    score = _format_score(getattr(report, "score", 0))

    # Cover
    for _ in range(7):
        document.add_paragraph()

    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run("BOOST RANKERS")
    run.bold = True
    run.font.size = Pt(11)
    run.font.color.rgb = RGBColor.from_string(TEAL)

    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run("Professional SEO Audit Report")
    run.bold = True
    run.font.size = Pt(27)
    run.font.color.rgb = RGBColor.from_string(NAVY)

    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run(website or "Website SEO Audit")
    run.font.size = Pt(11)
    run.font.color.rgb = RGBColor.from_string(MUTED)

    document.add_paragraph()

    cover = document.add_table(rows=5, cols=2)
    cover.alignment = WD_TABLE_ALIGNMENT.CENTER
    data = [
        ("Overall SEO Score", score),
        ("Audit Date", getattr(report, "generated_at", "N/A")),
        ("Pages Discovered", _audit_value(audit, "pages_discovered", default=0)),
        ("Pages Crawled", _audit_value(audit, "pages_crawled", default=0)),
        ("Pages Successful / Failed",
         f"{_audit_value(audit, 'pages_successful', default=0)} / "
         f"{_audit_value(audit, 'pages_failed', default=0)}"),
    ]
    for index, (label, value) in enumerate(data):
        _set_cell_text(cover.rows[index].cells[0], label, bold=True, color=BLUE)
        _set_cell_text(cover.rows[index].cells[1], value, color=TEXT)
        _shade_cell(cover.rows[index].cells[0], LIGHT)
        _set_cell_margins(cover.rows[index].cells[0])
        _set_cell_margins(cover.rows[index].cells[1])

    document.add_paragraph()
    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run(
        "Prepared from the completed audit stored in Boost Rankers AI SEO OS.\n"
        "Crawler evidence and AI interpretation are kept visibly separated."
    )
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor.from_string(MUTED)

    document.add_page_break()

    # Executive summary
    document.add_heading("1. Executive Summary", level=1)
    paragraph = document.add_paragraph()
    paragraph.add_run("Overall SEO score: ").bold = True
    paragraph.add_run(score)
    paragraph.add_run(
        f". The stored report contains {len(findings)} structured findings: "
        f"{counts['critical']} critical, {counts['high']} high, "
        f"{counts['medium']} medium and {counts['low']} low."
    )

    summary = _clean(getattr(report, "summary", "") or "")
    if summary:
        paragraph = document.add_paragraph(summary)
        paragraph.paragraph_format.space_after = Pt(8)

    # Scorecard
    document.add_heading("2. SEO Scorecard", level=1)
    scorecard = _parse_scorecard(content)
    if not scorecard:
        scorecard = {
            "Technical SEO": _format_score(_audit_value(audit, "technical_score", default=0)),
            "Content SEO": _format_score(_audit_value(audit, "content_score", default=0)),
            "Local SEO": _format_score(_audit_value(audit, "local_seo_score", "local_score", default=0)),
            "Schema": _format_score(_audit_value(audit, "schema_score", default=0)),
            "EEAT": _format_score(_audit_value(audit, "eeat_score", "eeat", default=0)),
            "AI Search": _format_score(_audit_value(audit, "ai_search_score", "ai_score", default=0)),
        }

    table = document.add_table(rows=1, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    _set_cell_text(table.rows[0].cells[0], "SEO Area", bold=True, color="FFFFFF")
    _set_cell_text(table.rows[0].cells[1], "Score", bold=True, color="FFFFFF")
    _shade_cell(table.rows[0].cells[0], BLUE)
    _shade_cell(table.rows[0].cells[1], BLUE)

    for area, value in scorecard.items():
        cells = table.add_row().cells
        _set_cell_text(cells[0], area)
        _set_cell_text(cells[1], value, bold=True, color=NAVY)
        _shade_cell(cells[1], LIGHT)
        _add_bottom_border(cells[0])
        _add_bottom_border(cells[1])

    # Crawl evidence
    document.add_heading("3. Real Crawl Evidence", level=1)
    metrics = [
        ("Pages discovered", _audit_value(audit, "pages_discovered", default=0)),
        ("Pages crawled", _audit_value(audit, "pages_crawled", default=0)),
        ("Pages successful", _audit_value(audit, "pages_successful", default=0)),
        ("Pages failed", _audit_value(audit, "pages_failed", default=0)),
        ("Internal links", _audit_value(audit, "internal_links", default=0)),
        ("External links", _audit_value(audit, "external_links", default=0)),
        ("Broken internal links", _audit_value(audit, "broken_internal_links", default=0)),
        ("Orphan resources/pages", _audit_value(audit, "orphan_pages_count", default=0)),
        ("Sitemap found", "Yes" if _audit_value(audit, "sitemap_found", default=False) else "No"),
        ("Robots.txt found", "Yes" if _audit_value(audit, "robots_found", default=False) else "No"),
        ("Schema detected", "Yes" if _audit_value(audit, "schema_found", default=False) else "No"),
    ]

    table = document.add_table(rows=1, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    _set_cell_text(table.rows[0].cells[0], "Measured metric", bold=True, color="FFFFFF")
    _set_cell_text(table.rows[0].cells[1], "Value", bold=True, color="FFFFFF")
    _shade_cell(table.rows[0].cells[0], TEAL)
    _shade_cell(table.rows[0].cells[1], TEAL)

    for label, value in metrics:
        cells = table.add_row().cells
        _set_cell_text(cells[0], label)
        _set_cell_text(cells[1], value, bold=True, color=NAVY)
        _shade_cell(cells[1], LIGHT)
        _add_bottom_border(cells[0])
        _add_bottom_border(cells[1])

    # Findings
    document.add_page_break()
    document.add_heading("4. Findings by SEO Skill", level=1)

    if not findings:
        document.add_paragraph(
            "No structured findings were available in the stored report content."
        )
    else:
        for index, finding in enumerate(findings, 1):
            severity = finding.severity.upper()
            severity_color = {
                "CRITICAL": CRITICAL,
                "HIGH": HIGH,
                "MEDIUM": MEDIUM,
                "LOW": LOW,
            }.get(severity, MUTED)

            card = document.add_table(rows=1, cols=1)
            cell = card.cell(0, 0)
            _shade_cell(cell, "F8FAFC")
            _set_cell_margins(cell, 110, 130, 110, 130)

            paragraph = cell.paragraphs[0]
            run = paragraph.add_run(f"{index:02d}  {severity}  ")
            run.bold = True
            run.font.size = Pt(8.5)
            run.font.color.rgb = RGBColor.from_string(severity_color)

            run = paragraph.add_run(finding.title)
            run.bold = True
            run.font.size = Pt(9.5)
            run.font.color.rgb = RGBColor.from_string(NAVY)

            if finding.url:
                paragraph = cell.add_paragraph()
                run = paragraph.add_run("Affected URL: ")
                run.bold = True
                run.font.size = Pt(8)
                run.font.color.rgb = RGBColor.from_string(BLUE)
                run = paragraph.add_run(finding.url)
                run.font.size = Pt(8)
                run.font.color.rgb = RGBColor.from_string(TEXT)

            for label, value in (
                ("What the crawl reports", finding.detail),
                ("Recommended action", finding.recommendation),
                ("Evidence", finding.evidence),
            ):
                if not value:
                    continue
                paragraph = cell.add_paragraph()
                run = paragraph.add_run(f"{label}: ")
                run.bold = True
                run.font.size = Pt(8)
                run.font.color.rgb = RGBColor.from_string(BLUE)
                run = paragraph.add_run(value)
                run.font.size = Pt(8)
                run.font.color.rgb = RGBColor.from_string(TEXT)

            document.add_paragraph().paragraph_format.space_after = Pt(1)

    # Page-level URL inventory
    document.add_page_break()
    document.add_heading("5. Page-Level URL Evidence", level=1)
    urls = _extract_urls(content)

    for finding in findings:
        if finding.url and finding.url not in urls:
            urls.append(finding.url)

    if urls:
        document.add_paragraph(
            "The URLs below are extracted from the stored audit report. "
            "No URL is invented by the export layer."
        )
        table = document.add_table(rows=1, cols=3)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        for index, heading in enumerate(("No.", "Page URL", "Related finding")):
            _set_cell_text(
                table.rows[0].cells[index],
                heading,
                bold=True,
                color="FFFFFF",
                size=8,
            )
            _shade_cell(table.rows[0].cells[index], BLUE)

        for index, url in enumerate(urls, 1):
            related = next(
                (
                    finding.title
                    for finding in findings
                    if finding.url == url
                ),
                "URL referenced by audit evidence",
            )
            cells = table.add_row().cells
            _set_cell_text(cells[0], index, bold=True, color=NAVY, size=7)
            _set_cell_text(cells[1], url, size=7)
            _set_cell_text(cells[2], related, size=7)
            for cell in cells:
                _set_cell_margins(cell, 70, 70, 70, 70)
                _add_bottom_border(cell)
    else:
        document.add_paragraph(
            "No explicit page URLs were available in the stored report content."
        )

    # Data integrity
    document.add_heading("6. Data Integrity", level=1)
    integrity = [
        ("Crawler verified", "HTTP status, titles, meta descriptions, headings, canonicals, robots, schema, links and crawl metrics when present in the stored evidence."),
        ("Derived metrics", "Duplicate/missing counts and other metrics calculated from crawler evidence."),
        ("AI analysis", "Priorities, impact interpretation and recommendations produced by the SEO skills."),
        ("External data required", "Google rankings, Search Console performance, backlink authority/referring domains and competitor rankings require their respective integrations."),
    ]
    table = document.add_table(rows=1, cols=2)
    for j, heading in enumerate(("Evidence class", "Meaning")):
        _set_cell_text(table.rows[0].cells[j], heading, bold=True, color="FFFFFF")
        _shade_cell(table.rows[0].cells[j], BLUE)
    for label, value in integrity:
        cells = table.add_row().cells
        _set_cell_text(cells[0], label, bold=True, color=NAVY)
        _set_cell_text(cells[1], value)
        _shade_cell(cells[0], LIGHT)
        _add_bottom_border(cells[0])
        _add_bottom_border(cells[1])

    document.add_heading("7. Recommended Action Plan", level=1)
    actions = [
        "P0 — Resolve critical technical and indexability findings first.",
        "P0 — Fix duplicate titles, missing metadata, H1 problems and broken internal links identified by the crawl.",
        "P1 — Improve internal architecture and reduce excessive crawl depth.",
        "P1 — Verify local entity, Contact/About, schema and trust signals.",
        "P1 — Add or correct Article/BlogPosting/FAQPage/Person markup where the content supports it.",
        "P2 — Connect Search Console and backlink/competitor providers before reporting external ranking metrics.",
    ]
    for action in actions:
        document.add_paragraph(action, style="List Number")

    paragraph = document.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run(
        "BOOST RANKERS AI SEO OS  •  Professional evidence-based reporting"
    )
    run.bold = True
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor.from_string(MUTED)

    output = io.BytesIO()
    document.save(output)
    output.seek(0)

    filename = _safe_filename(
        getattr(report, "title", "seo-audit-report"),
        "docx",
    )
    return output.getvalue(), filename


# ---------------- PDF ----------------

def _pdf_color(hex_value: str):
    return colors.HexColor("#" + hex_value)


def _pdf_header_footer(canvas, doc):
    canvas.saveState()
    width, height = A4
    canvas.setFont("Helvetica-Bold", 7.5)
    canvas.setFillColor(_pdf_color(BLUE))
    canvas.drawString(18 * mm, height - 10 * mm, "BOOST RANKERS  •  AI SEO OS")

    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(_pdf_color(MUTED))
    canvas.drawString(18 * mm, 8 * mm, "Evidence-based SEO audit")
    canvas.drawRightString(192 * mm, 8 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build_pdf(report: Any) -> tuple[bytes, str]:
    output = io.BytesIO()
    document = SimpleDocTemplate(
        output,
        pagesize=A4,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=17 * mm,
        bottomMargin=14 * mm,
        title=getattr(report, "title", "SEO Audit Report"),
        author="Boost Rankers AI SEO OS",
    )

    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "BRTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=23,
        leading=27,
        textColor=_pdf_color(NAVY),
        alignment=TA_CENTER,
        spaceAfter=10,
    )
    subtitle = ParagraphStyle(
        "BRSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        textColor=_pdf_color(MUTED),
        alignment=TA_CENTER,
        spaceAfter=8,
    )
    h1 = ParagraphStyle(
        "BRH1",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        textColor=_pdf_color(NAVY),
        spaceBefore=6,
        spaceAfter=8,
    )
    h2 = ParagraphStyle(
        "BRH2",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=_pdf_color(BLUE),
        spaceBefore=5,
        spaceAfter=5,
    )
    body = ParagraphStyle(
        "BRBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=_pdf_color(TEXT),
        spaceAfter=5,
    )
    small = ParagraphStyle(
        "BRSmall",
        parent=body,
        fontSize=7.5,
        leading=10,
    )
    center_small = ParagraphStyle(
        "BRCenterSmall",
        parent=small,
        alignment=TA_CENTER,
    )
    card_title = ParagraphStyle(
        "BRCardTitle",
        parent=body,
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=_pdf_color(NAVY),
    )

    website = _extract_website(report)
    audit = getattr(report, "audit", None)
    content = _clean(getattr(report, "content", "") or "")
    findings = extract_findings(content)
    counts = _issue_counts(findings)
    score = _format_score(getattr(report, "score", 0))

    story: list[Any] = []

    story.extend(
        [
            Spacer(1, 45 * mm),
            Paragraph("BOOST RANKERS", ParagraphStyle(
                "brand",
                parent=center_small,
                fontName="Helvetica-Bold",
                fontSize=10,
                textColor=_pdf_color(TEAL),
            )),
            Paragraph("Professional SEO Audit Report", title),
            Paragraph(website or "Website SEO Audit", subtitle),
        ]
    )

    cover_data = [
        [Paragraph("<b>Overall SEO Score</b>", small), Paragraph(score, small)],
        [Paragraph("<b>Audit Date</b>", small), Paragraph(_clean(getattr(report, "generated_at", "N/A")), small)],
        [Paragraph("<b>Pages Discovered</b>", small), Paragraph(_clean(_audit_value(audit, "pages_discovered", default=0)), small)],
        [Paragraph("<b>Pages Crawled</b>", small), Paragraph(_clean(_audit_value(audit, "pages_crawled", default=0)), small)],
        [
            Paragraph("<b>Successful / Failed</b>", small),
            Paragraph(
                f"{_audit_value(audit, 'pages_successful', default=0)} / "
                f"{_audit_value(audit, 'pages_failed', default=0)}",
                small,
            ),
        ],
    ]
    cover_table = Table(cover_data, colWidths=[65 * mm, 65 * mm])
    cover_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), _pdf_color(LIGHT)),
                ("BOX", (0, 0), (-1, -1), 0.5, _pdf_color(BORDER)),
                ("INNERGRID", (0, 0), (-1, -1), 0.35, _pdf_color(BORDER)),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story += [Spacer(1, 8 * mm), cover_table]
    story += [
        Spacer(1, 8 * mm),
        Paragraph(
            "Prepared from the completed audit stored in Boost Rankers AI SEO OS. "
            "Crawler evidence and AI interpretation are kept visibly separated.",
            center_small,
        ),
        PageBreak(),
    ]

    story.append(Paragraph("1. Executive Summary", h1))
    story.append(
        Paragraph(
            f"<b>Overall SEO score:</b> {score}. "
            f"The stored report contains {len(findings)} structured findings: "
            f"{counts['critical']} critical, {counts['high']} high, "
            f"{counts['medium']} medium and {counts['low']} low.",
            body,
        )
    )

    summary = _clean(getattr(report, "summary", "") or "")
    if summary:
        story.append(Paragraph(summary, body))

    story.append(Paragraph("2. SEO Scorecard", h1))
    scorecard = _parse_scorecard(content)
    if not scorecard:
        scorecard = {
            "Technical SEO": _format_score(_audit_value(audit, "technical_score", default=0)),
            "Content SEO": _format_score(_audit_value(audit, "content_score", default=0)),
            "Local SEO": _format_score(_audit_value(audit, "local_seo_score", "local_score", default=0)),
            "Schema": _format_score(_audit_value(audit, "schema_score", default=0)),
            "EEAT": _format_score(_audit_value(audit, "eeat_score", "eeat", default=0)),
            "AI Search": _format_score(_audit_value(audit, "ai_search_score", "ai_score", default=0)),
        }

    score_rows = [[Paragraph("<b>SEO Area</b>", small), Paragraph("<b>Score</b>", small)]]
    score_rows += [[Paragraph(_clean(k), small), Paragraph(f"<b>{_clean(v)}</b>", small)] for k, v in scorecard.items()]
    score_table = Table(score_rows, colWidths=[100 * mm, 30 * mm])
    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _pdf_color(BLUE)),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("BACKGROUND", (1, 1), (1, -1), _pdf_color(LIGHT)),
                ("GRID", (0, 0), (-1, -1), 0.35, _pdf_color(BORDER)),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.append(score_table)

    story.append(Paragraph("3. Real Crawl Evidence", h1))
    metric_rows = [[Paragraph("<b>Measured metric</b>", small), Paragraph("<b>Value</b>", small)]]
    metrics = [
        ("Pages discovered", _audit_value(audit, "pages_discovered", default=0)),
        ("Pages crawled", _audit_value(audit, "pages_crawled", default=0)),
        ("Pages successful", _audit_value(audit, "pages_successful", default=0)),
        ("Pages failed", _audit_value(audit, "pages_failed", default=0)),
        ("Internal links", _audit_value(audit, "internal_links", default=0)),
        ("External links", _audit_value(audit, "external_links", default=0)),
        ("Broken internal links", _audit_value(audit, "broken_internal_links", default=0)),
        ("Orphan resources/pages", _audit_value(audit, "orphan_pages_count", default=0)),
        ("Sitemap found", "Yes" if _audit_value(audit, "sitemap_found", default=False) else "No"),
        ("Robots.txt found", "Yes" if _audit_value(audit, "robots_found", default=False) else "No"),
        ("Schema detected", "Yes" if _audit_value(audit, "schema_found", default=False) else "No"),
    ]
    metric_rows += [[Paragraph(_clean(k), small), Paragraph(_clean(v), small)] for k, v in metrics]
    metric_table = Table(metric_rows, colWidths=[100 * mm, 30 * mm])
    metric_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _pdf_color(TEAL)),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("BACKGROUND", (1, 1), (1, -1), _pdf_color(LIGHT)),
                ("GRID", (0, 0), (-1, -1), 0.35, _pdf_color(BORDER)),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story += [metric_table, PageBreak(), Paragraph("4. Findings by SEO Skill", h1)]

    if not findings:
        story.append(Paragraph("No structured findings were available in the stored report content.", body))
    else:
        for index, finding in enumerate(findings, 1):
            severity = finding.severity.upper()
            severity_color = {
                "CRITICAL": CRITICAL,
                "HIGH": HIGH,
                "MEDIUM": MEDIUM,
                "LOW": LOW,
            }.get(severity, MUTED)

            rows = [
                [
                    Paragraph(
                        f"<font color='#{severity_color}'><b>{index:02d}  {severity}</b></font>",
                        small,
                    ),
                    Paragraph(f"<b>{_clean(finding.title)}</b>", card_title),
                ]
            ]
            if finding.url:
                rows.append(
                    [
                        Paragraph("<b>Affected URL</b>", small),
                        Paragraph(_clean(finding.url), small),
                    ]
                )
            for label, value in (
                ("What the crawl reports", finding.detail),
                ("Recommended action", finding.recommendation),
                ("Evidence", finding.evidence),
            ):
                if value:
                    rows.append(
                        [
                            Paragraph(f"<b>{label}</b>", small),
                            Paragraph(_clean(value), small),
                        ]
                    )

            table = Table(rows, colWidths=[42 * mm, 88 * mm], repeatRows=1)
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), _pdf_color("F8FAFC")),
                        ("BOX", (0, 0), (-1, -1), 0.6, _pdf_color(BORDER)),
                        ("INNERGRID", (0, 0), (-1, -1), 0.3, _pdf_color(BORDER)),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 7),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                        ("TOPPADDING", (0, 0), (-1, -1), 6),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ]
                )
            )
            story += [KeepTogether(table), Spacer(1, 3 * mm)]

    story += [PageBreak(), Paragraph("5. Page-Level URL Evidence", h1)]

    urls = _extract_urls(content)
    for finding in findings:
        if finding.url and finding.url not in urls:
            urls.append(finding.url)

    if urls:
        story.append(
            Paragraph(
                "URLs are extracted from the stored audit content. "
                "The export layer does not invent page URLs.",
                body,
            )
        )
        rows = [[
            Paragraph("<b>No.</b>", small),
            Paragraph("<b>Page URL</b>", small),
            Paragraph("<b>Related finding</b>", small),
        ]]
        for index, url in enumerate(urls, 1):
            related = next(
                (
                    finding.title
                    for finding in findings
                    if finding.url == url
                ),
                "URL referenced by audit evidence",
            )
            rows.append(
                [
                    Paragraph(str(index), small),
                    Paragraph(_clean(url), small),
                    Paragraph(_clean(related), small),
                ]
            )

        table = Table(rows, colWidths=[12 * mm, 75 * mm, 43 * mm], repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), _pdf_color(BLUE)),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.35, _pdf_color(BORDER)),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 5),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No explicit page URLs were available in the stored report content.", body))

    story.append(Paragraph("6. Data Integrity", h1))
    integrity = [
        ("Crawler verified", "HTTP status, titles, meta descriptions, headings, canonicals, robots, schema, links and crawl metrics when present."),
        ("Derived metrics", "Counts calculated from crawler evidence."),
        ("AI analysis", "Priorities, impact interpretation and recommendations from SEO skills."),
        ("External data required", "Search Console, backlink authority and competitor ranking metrics require their integrations."),
    ]
    rows = [[Paragraph("<b>Evidence class</b>", small), Paragraph("<b>Meaning</b>", small)]]
    rows += [[Paragraph(f"<b>{a}</b>", small), Paragraph(b, small)] for a, b in integrity]
    table = Table(rows, colWidths=[42 * mm, 88 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _pdf_color(BLUE)),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("BACKGROUND", (0, 1), (0, -1), _pdf_color(LIGHT)),
                ("GRID", (0, 0), (-1, -1), 0.35, _pdf_color(BORDER)),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(table)

    story.append(Paragraph("7. Recommended Action Plan", h1))
    actions = [
        "P0 — Resolve critical technical and indexability findings first.",
        "P0 — Fix duplicate titles, missing metadata, H1 problems and broken internal links.",
        "P1 — Improve internal architecture and reduce excessive crawl depth.",
        "P1 — Verify local entity, Contact/About, schema and trust signals.",
        "P1 — Add or correct Article/BlogPosting/FAQPage/Person markup where supported by the content.",
        "P2 — Connect Search Console and backlink/competitor providers before reporting external ranking metrics.",
    ]
    for action in actions:
        story.append(Paragraph("• " + _clean(action), body))

    document.build(
        story,
        onFirstPage=_pdf_header_footer,
        onLaterPages=_pdf_header_footer,
    )
    output.seek(0)

    filename = _safe_filename(
        getattr(report, "title", "seo-audit-report"),
        "pdf",
    )
    return output.getvalue(), filename
