"""add ai_credits to companies

Revision ID: 00952caf807f
Revises: 7b3eec2e7eaa
Create Date: 2026-08-11 21:39:35.858958

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '00952caf807f'
down_revision: Union[str, Sequence[str], None] = '7b3eec2e7eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###