"""add encrypted anthropic settings

Revision ID: 208c9f8cbb66
Revises: 4bdcf059f0a1
Create Date: 2026-08-15 11:12:45.176092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '208c9f8cbb66'
down_revision: Union[str, Sequence[str], None] = '4bdcf059f0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "companies",
        sa.Column(
            "anthropic_api_key_encrypted",
            sa.Text(),
            nullable=True,
        ),
    )

    op.add_column(
        "companies",
        sa.Column(
            "anthropic_api_status",
            sa.String(length=50),
            nullable=False,
            server_default="not_configured",
        ),
    )

    op.add_column(
        "companies",
        sa.Column(
            "anthropic_api_last_checked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    # Remove the temporary server default so future inserts
    # are controlled by the SQLAlchemy model/application.
    op.alter_column(
        "companies",
        "anthropic_api_status",
        server_default=None,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'anthropic_api_last_checked_at')
    op.drop_column('companies', 'anthropic_api_status')
    op.drop_column('companies', 'anthropic_api_key_encrypted')
    # ### end Alembic commands ###