"""add ai_credits to companies

Revision ID: 25e429918c9b
Revises: b9fed3be2c90
Create Date: 2026-08-11 00:53:11.468784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '25e429918c9b'
down_revision: Union[str, Sequence[str], None] = 'b9fed3be2c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('companies', sa.Column('slug', sa.String(length=200), nullable=False))
    op.add_column('companies', sa.Column('legal_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('postal_code', sa.String(length=30), nullable=True))
    op.add_column('companies', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('timezone', sa.String(length=100), nullable=False))
    op.add_column('companies', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('favicon_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('primary_color', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('secondary_color', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('subscription_plan', sa.String(length=50), nullable=False))
    op.add_column('companies', sa.Column('subscription_status', sa.String(length=50), nullable=False))
    op.add_column('companies', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('webhook_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('max_users', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('max_projects', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('ai_credits', sa.Integer(), nullable=False))
    op.create_index('idx_company_active', 'companies', ['is_active'], unique=False)
    op.create_index('idx_company_email', 'companies', ['email'], unique=False)
    op.create_index('idx_company_plan', 'companies', ['subscription_plan'], unique=False)
    op.create_index('idx_company_slug', 'companies', ['slug'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index('idx_company_slug', table_name='companies')
    op.drop_index('idx_company_plan', table_name='companies')
    op.drop_index('idx_company_email', table_name='companies')
    op.drop_index('idx_company_active', table_name='companies')
    op.drop_column('companies', 'ai_credits')
    op.drop_column('companies', 'max_projects')
    op.drop_column('companies', 'max_users')
    op.drop_column('companies', 'is_verified')
    op.drop_column('companies', 'is_active')
    op.drop_column('companies', 'webhook_url')
    op.drop_column('companies', 'api_key')
    op.drop_column('companies', 'trial_ends_at')
    op.drop_column('companies', 'subscription_status')
    op.drop_column('companies', 'subscription_plan')
    op.drop_column('companies', 'secondary_color')
    op.drop_column('companies', 'primary_color')
    op.drop_column('companies', 'favicon_url')
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'currency')
    op.drop_column('companies', 'timezone')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'postal_code')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'address_line2')
    op.drop_column('companies', 'address_line1')
    op.drop_column('companies', 'domain')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'legal_name')
    op.drop_column('companies', 'slug')
    op.drop_column('companies', 'name')
    # ### end Alembic commands ###