"""update reports table with audit_id score etc

Revision ID: 3a2dfd8d40ba
Revises: 9d7fabc80695
Create Date: 2026-08-11 16:06:36.775851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '3a2dfd8d40ba'
down_revision: Union[str, Sequence[str], None] = '9d7fabc80695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('audit_id', sa.String(length=36), nullable=True))
    op.add_column('reports', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('score', sa.Float(), nullable=False))
    op.add_column('reports', sa.Column('format', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_reports_audit_id'), 'reports', ['audit_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'audits', ['audit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_audit_id'), table_name='reports')
    op.drop_column('reports', 'generated_at')
    op.drop_column('reports', 'format')
    op.drop_column('reports', 'score')
    op.drop_column('reports', 'summary')
    op.drop_column('reports', 'audit_id')
    # ### end Alembic commands ###