"""add ai_credits and audit_id

Revision ID: 44c2a0fe1350
Revises: 619c53510143
Create Date: 2026-08-11 20:20:00.347420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '44c2a0fe1350'
down_revision: Union[str, Sequence[str], None] = '619c53510143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###