"""add ai_credits and audit_id

Revision ID: 619c53510143
Revises: f31ebc6874ff
Create Date: 2026-08-11 17:44:15.504414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '619c53510143'
down_revision: Union[str, Sequence[str], None] = 'f31ebc6874ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###