"""add competitors table

Revision ID: 7b3eec2e7eaa
Revises: 44c2a0fe1350
Create Date: 2026-08-11 21:31:12.753114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7b3eec2e7eaa'
down_revision: Union[str, Sequence[str], None] = '44c2a0fe1350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('traffic', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.Integer(), nullable=False),
    sa.Column('backlinks', sa.Integer(), nullable=False),
    sa.Column('da', sa.Float(), nullable=False),
    sa.Column('gap', sa.Integer(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_company_id'), 'competitors', ['company_id'], unique=False)
    op.create_index(op.f('ix_competitors_domain'), 'competitors', ['domain'], unique=False)
    op.create_index(op.f('ix_competitors_id'), 'competitors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitors_id'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_domain'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_company_id'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###