"""add internal_linking_suggestions table

Revision ID: 877d22c5e409
Revises: 042339713c23
Create Date: 2026-08-12 09:02:33.465150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '877d22c5e409'
down_revision: Union[str, Sequence[str], None] = '042339713c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_linking_suggestions_company_id'), table_name='internal_linking_suggestions')
    op.drop_index(op.f('ix_internal_linking_suggestions_id'), table_name='internal_linking_suggestions')
    op.drop_table('internal_linking_suggestions')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_linking_suggestions',
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('suggestions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('internal_linking_suggestions_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('internal_linking_suggestions_pkey'))
    )
    op.create_index(op.f('ix_internal_linking_suggestions_id'), 'internal_linking_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_internal_linking_suggestions_company_id'), 'internal_linking_suggestions', ['company_id'], unique=False)
    # ### end Alembic commands ###