"""update reports table

Revision ID: 8d727923e9db
Revises: 3a2dfd8d40ba
Create Date: 2026-08-11 16:09:28.377643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '8d727923e9db'
down_revision: Union[str, Sequence[str], None] = '3a2dfd8d40ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###