"""add backlink tables

Revision ID: 9111e5c9dce3
Revises: 877d22c5e409
Create Date: 2026-08-12 09:40:53.250137

This migration is intentionally a no-op.

The backlink-related tables already exist in the database from
previous migrations. The original autogenerated migration attempted
to drop and recreate them, which is unsafe because outreach_emails
contains a foreign key referencing backlink_opportunities.

Revision ID: 9111e5c9dce3
"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9111e5c9dce3"
down_revision: Union[str, Sequence[str], None] = "877d22c5e409"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    No schema changes are required.

    The backlink tables already exist in the database. The original
    autogenerated migration attempted to drop and recreate them,
    which would destroy existing data and break foreign-key
    dependencies.
    """
    pass


def downgrade() -> None:
    """
    No schema changes are reversed.

    This revision does not introduce a new database structure.
    """
    pass