"""add competitors table

Revision ID: b91e5730aad5
Revises: 00952caf807f
Create Date: 2026-08-11 22:59:19.411533

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b91e5730aad5'
down_revision: Union[str, Sequence[str], None] = '00952caf807f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competitors', 'traffic',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('competitors', 'da',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_competitors_domain'), table_name='competitors')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_competitors_domain'), 'competitors', ['domain'], unique=False)
    op.alter_column('competitors', 'da',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('competitors', 'traffic',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###