"""add audit_id and relationship to reports

Revision ID: f31ebc6874ff
Revises: fee8ad0a9f88
Create Date: 2026-08-11 17:10:10.481228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'f31ebc6874ff'
down_revision: Union[str, Sequence[str], None] = 'fee8ad0a9f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###