"""complete_company_model

Revision ID: fe1301941ffe
Revises: 344fbf582bbd
Create Date: 2026-08-05 21:29:08.639507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe1301941ffe'
down_revision: Union[str, Sequence[str], None] = '344fbf582bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.String(length=150), nullable=True))
    op.add_column('companies', sa.Column('company_size', sa.String(length=20), nullable=False))
    op.add_column('companies', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('tax_number', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('alternate_phone', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('whatsapp', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('support_email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('sales_email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('language', sa.String(length=10), nullable=False))
    op.add_column('companies', sa.Column('date_format', sa.String(length=20), nullable=False))
    op.add_column('companies', sa.Column('time_format', sa.String(length=20), nullable=False))
    op.add_column('companies', sa.Column('cover_image', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('accent_color', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('font_family', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('dark_mode_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('white_label_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('custom_domain', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('billing_cycle', sa.String(length=20), nullable=False))
    op.add_column('companies', sa.Column('trial_starts_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('subscription_starts_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('next_billing_date', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('companies', sa.Column('credit_balance', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('max_clients', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('max_monthly_audits', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('max_storage_gb', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('api_calls_per_month', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('used_storage_gb', sa.Float(), nullable=False))
    op.add_column('companies', sa.Column('used_api_calls', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('active_users', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('active_clients', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('active_projects', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('google_search_console_connected', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('google_analytics_connected', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('google_business_profile_connected', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('google_tag_manager_connected', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('bing_webmaster_connected', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('openai_api_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('anthropic_api_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('pagespeed_api_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('google_maps_api_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('smtp_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('webhook_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('slack_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('zapier_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('default_country', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('default_language', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('default_search_engine', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('default_device', sa.String(length=30), nullable=True))
    op.add_column('companies', sa.Column('default_audit_schedule', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('enable_ai_recommendations', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('enable_auto_audits', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('enable_email_reports', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('enable_white_label_reports', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('total_users', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('total_clients', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('total_projects', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('total_audits', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('total_reports', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('average_seo_score', sa.Float(), nullable=False))
    op.add_column('companies', sa.Column('total_keywords', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('total_backlinks', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('monthly_api_requests', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('companies', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('api_access_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('ip_restriction_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('session_timeout_minutes', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('password_expiry_days', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('openai_api_key', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('anthropic_api_key', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('google_pagespeed_api_key', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('google_maps_api_key', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('smtp_username', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('smtp_password', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('smtp_encryption', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('smtp_from_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('smtp_from_email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('slack_webhook', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('zapier_webhook', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('discord_webhook', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('internal_notes', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('companies', 'subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('companies', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('companies', 'trial_ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_company_active'), table_name='companies')
    op.drop_index(op.f('idx_company_email'), table_name='companies')
    op.drop_index(op.f('idx_company_plan'), table_name='companies')
    op.drop_index(op.f('idx_company_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=False)
    op.create_index('ix_company_country', 'companies', ['country'], unique=False)
    op.create_index('ix_company_created_at', 'companies', ['created_at'], unique=False)
    op.create_index('ix_company_name', 'companies', ['name'], unique=False)
    op.create_index('ix_company_plan', 'companies', ['subscription_plan'], unique=False)
    op.create_index('ix_company_slug', 'companies', ['slug'], unique=False)
    op.create_index('ix_company_status', 'companies', ['status'], unique=False)
    op.drop_column('companies', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('ix_company_status', table_name='companies')
    op.drop_index('ix_company_slug', table_name='companies')
    op.drop_index('ix_company_plan', table_name='companies')
    op.drop_index('ix_company_name', table_name='companies')
    op.drop_index('ix_company_created_at', table_name='companies')
    op.drop_index('ix_company_country', table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('idx_company_slug'), 'companies', ['slug'], unique=False)
    op.create_index(op.f('idx_company_plan'), 'companies', ['subscription_plan'], unique=False)
    op.create_index(op.f('idx_company_email'), 'companies', ['email'], unique=False)
    op.create_index(op.f('idx_company_active'), 'companies', ['is_active'], unique=False)
    op.alter_column('companies', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('companies', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'trial_ends_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('companies', 'subscription_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('companies', 'subscription_plan',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('companies', 'version')
    op.drop_column('companies', 'tags')
    op.drop_column('companies', 'internal_notes')
    op.drop_column('companies', 'notes')
    op.drop_column('companies', 'discord_webhook')
    op.drop_column('companies', 'zapier_webhook')
    op.drop_column('companies', 'slack_webhook')
    op.drop_column('companies', 'smtp_from_email')
    op.drop_column('companies', 'smtp_from_name')
    op.drop_column('companies', 'smtp_encryption')
    op.drop_column('companies', 'smtp_password')
    op.drop_column('companies', 'smtp_username')
    op.drop_column('companies', 'smtp_port')
    op.drop_column('companies', 'smtp_host')
    op.drop_column('companies', 'google_maps_api_key')
    op.drop_column('companies', 'google_pagespeed_api_key')
    op.drop_column('companies', 'anthropic_api_key')
    op.drop_column('companies', 'openai_api_key')
    op.drop_column('companies', 'password_expiry_days')
    op.drop_column('companies', 'session_timeout_minutes')
    op.drop_column('companies', 'ip_restriction_enabled')
    op.drop_column('companies', 'api_access_enabled')
    op.drop_column('companies', 'two_factor_enabled')
    op.drop_column('companies', 'is_archived')
    op.drop_column('companies', 'status')
    op.drop_column('companies', 'monthly_api_requests')
    op.drop_column('companies', 'total_backlinks')
    op.drop_column('companies', 'total_keywords')
    op.drop_column('companies', 'average_seo_score')
    op.drop_column('companies', 'total_reports')
    op.drop_column('companies', 'total_audits')
    op.drop_column('companies', 'total_projects')
    op.drop_column('companies', 'total_clients')
    op.drop_column('companies', 'total_users')
    op.drop_column('companies', 'enable_white_label_reports')
    op.drop_column('companies', 'enable_email_reports')
    op.drop_column('companies', 'enable_auto_audits')
    op.drop_column('companies', 'enable_ai_recommendations')
    op.drop_column('companies', 'default_audit_schedule')
    op.drop_column('companies', 'default_device')
    op.drop_column('companies', 'default_search_engine')
    op.drop_column('companies', 'default_language')
    op.drop_column('companies', 'default_country')
    op.drop_column('companies', 'zapier_enabled')
    op.drop_column('companies', 'slack_enabled')
    op.drop_column('companies', 'webhook_enabled')
    op.drop_column('companies', 'smtp_enabled')
    op.drop_column('companies', 'google_maps_api_enabled')
    op.drop_column('companies', 'pagespeed_api_enabled')
    op.drop_column('companies', 'anthropic_api_enabled')
    op.drop_column('companies', 'openai_api_enabled')
    op.drop_column('companies', 'bing_webmaster_connected')
    op.drop_column('companies', 'google_tag_manager_connected')
    op.drop_column('companies', 'google_business_profile_connected')
    op.drop_column('companies', 'google_analytics_connected')
    op.drop_column('companies', 'google_search_console_connected')
    op.drop_column('companies', 'active_projects')
    op.drop_column('companies', 'active_clients')
    op.drop_column('companies', 'active_users')
    op.drop_column('companies', 'used_api_calls')
    op.drop_column('companies', 'used_storage_gb')
    op.drop_column('companies', 'api_calls_per_month')
    op.drop_column('companies', 'max_storage_gb')
    op.drop_column('companies', 'max_monthly_audits')
    op.drop_column('companies', 'max_clients')
    op.drop_column('companies', 'credit_balance')
    op.drop_column('companies', 'monthly_price')
    op.drop_column('companies', 'next_billing_date')
    op.drop_column('companies', 'subscription_expires_at')
    op.drop_column('companies', 'subscription_starts_at')
    op.drop_column('companies', 'trial_starts_at')
    op.drop_column('companies', 'billing_cycle')
    op.drop_column('companies', 'custom_domain')
    op.drop_column('companies', 'white_label_enabled')
    op.drop_column('companies', 'dark_mode_enabled')
    op.drop_column('companies', 'font_family')
    op.drop_column('companies', 'accent_color')
    op.drop_column('companies', 'cover_image')
    op.drop_column('companies', 'time_format')
    op.drop_column('companies', 'date_format')
    op.drop_column('companies', 'language')
    op.drop_column('companies', 'longitude')
    op.drop_column('companies', 'latitude')
    op.drop_column('companies', 'billing_email')
    op.drop_column('companies', 'sales_email')
    op.drop_column('companies', 'support_email')
    op.drop_column('companies', 'whatsapp')
    op.drop_column('companies', 'alternate_phone')
    op.drop_column('companies', 'tax_number')
    op.drop_column('companies', 'registration_number')
    op.drop_column('companies', 'founded_year')
    op.drop_column('companies', 'company_size')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###