"""add reports relationship to audit

Revision ID: fee8ad0a9f88
Revises: 8d727923e9db
Create Date: 2026-08-11 17:01:08.219170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'fee8ad0a9f88'
down_revision: Union[str, Sequence[str], None] = '8d727923e9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###